ncr_cached_urls = {
    "/alfresco/flammability/local/": "community",
    "/alfresco/veg_type/local/": "community",
    "/beetles/point/": "community",
    "/elevation/point/": "community",
    "/taspr/point/": "community",
    "/indicators/base/point/": "community",
    "/ncr/permafrost/point/": "community",
    "/eds/hydrology/point/": "community",
    "/alfresco/flammability/area/": "area",
    "/alfresco/veg_type/area/": "area",
    "/beetles/area/": "area",
    "/elevation/area/": "area",
    "/taspr/area/": "area",
    "/indicators/base/area/": "area",
}

eds_cached_url = "/eds/all/"

ardac_cached_urls = [
    "/cmip6/point/{latitude}/{longitude}?vars=tas,tasmax,tasmin",
    "/cmip6/point/{latitude}/{longitude}?vars=sfcWind,uas,vas",
    "/cmip6/point/{latitude}/{longitude}?vars=psl,ts",
    "/cmip6/point/{latitude}/{longitude}?vars=pr",
    "/cmip6/point/{latitude}/{longitude}?vars=evspsbl",
    "/cmip6/point/{latitude}/{longitude}?vars=rsds,rlds,hfss,hfls,clt",
    "/cmip6/point/{latitude}/{longitude}?vars=prsn,snw",
    "/indicators/cmip6/point/",
    "/indicators/base/point/",
    "/temperature_anomalies/point/",
    "/permafrost/point/gipl/",
    "/alfresco/flammability/local/",
    "/alfresco/veg_type/local/",
    "/landfastice/point/",
    "/degree_days/heating/",
    "/degree_days/below_zero/",
    "/degree_days/thawing_index/",
    "/degree_days/freezing_index/",
    "/beetles/point/",
    "/precipitation/frequency/point/",
    "/seaice/point/",
    "/hydrology/point/",
]
