cached_urls = [
    "/eds/all/",
    "/alfresco/flammability/local/",
    "/alfresco/veg_type/local/",
    "/beetles/point/",
    "/elevation/point/",
    "/taspr/point/",
    "/indicators/base/point/",
    "/ncr/permafrost/point/",
    "/eds/hydrology/point/",
    "/alfresco/flammability/area/",
    "/alfresco/veg_type/area/",
    "/beetles/area/",
    "/elevation/area/",
    "/taspr/area/",
    "/indicators/base/area/",
]
