"""Lookup tables for the regridding Prefect flow."""

# use this list to validate variables
# these were copied from the transfers/config.py in the cmip6-utils repo and include the WRF variables

valid_vars = [
    'clt',
    'evspsbl',
    'hfls',
    'hfss',
    'hus',
    'huss',
    'mrro',
    'mrsol',
    'mrsos',
    'orog',
    'pr',
    'prsn',
    'ps',
    'psl',
    'rlds',
    'rls',
    'rsds',
    'rss',
    'sfcWind',
    'sfcWindmax',
    'sftlf',
    'sftof',
    'siconc',
    'sithick',
    'snd',
    'snw',
    'ta',
    'tas',
    'tasmax',
    'tasmin',
    'tos',
    'ts',
    'tsl',
    'ua',
    'uas',
    'va',
    'vas',
    'zg',
    ]