name: fire_map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal
  - geopandas
  - matplotlib
  - pandas
  - scikit-learn
  - folium
  - pyproj
  - requests
  - shapely
  - fiona
  - rtree
  - pip
  - pip:
      - branca
