name: cusp
channels:
  - conda-forge
dependencies:
  - python=3.9
  - prefect=2.14.2
  - requests
  - packaging
  - pandas
  - geopandas
  - pyogrio
  - libgdal-core # provides the ogr2ogr binary the prep script shells out to
