name: smokeybear
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - gdal
  - numpy
  - matplotlib
  - pandas
  - pip
  - proj
  - poppler
  - libgdal
  - libnetcdf
  - geotiff
  - hdf4
  - hdf5
  - cairo
  - freetype
  - fontconfig
  - curl
  - openjpeg
  - jpeg
  - zlib
  - libxml2
  - libpq
  - postgresql
  - libspatialite
  - json-c
  - tiledb
  - xerces-c
  - krb5
  - six
  - setuptools
  - wheel
